name: logorrhoea
favicon: null
layout_spectrum: 0.6817457254510373
typography_spectrum: 0.6549212504178286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbfdfd'
    - '#768ea0'
    - '#3e5b75'
    - '#d6a013'
  brandStrength: 0.75
  lightness: 0.6908849074970931
  saturation: 0.6996278129518032
  rhythmicContrast: 0.348031077766791
purpose: []
